### ISSUE TITLE
Add poetry?

### ISSUE THREAD

**Issue by jcsumlin** [michealespinola/reddit.wikidownloader#1]
I'm no expert when it come to poetry specifically but some sort of dependency managemet would be great here.

[Documentation if you're interested](https://python-poetry.org/)

**Comment by michealespinola** [comment]
I'm a bit on the inexperienced side with python, so I am definitely interested in how to better do this. Thank you, I will check this out.

**Comment by michealespinola** [comment]
`pyproject.toml` and `requirements.txt` files created. I hope I got it right. Let me know if I didnt.

_Better late than never!_
